### ISSUE TITLE
SimpleForm styles

### ISSUE THREAD

**Issue by atstockland** [trimentor/pwdcalc#4]
This gem is the best one I have found so far (and I have tried nearly all similar ones).  However, your styles overwrite simple_form styles...  For example .pwdcalc_simple replaces simple_forms .form-control class.  If I get time Ill fork and try to submit a PR.

**Comment by trimentor** [comment]
That sounds great!

**Comment by trimentor** [comment]
In the next release I'll remove the custom input for SimpleForm and Formtastic.
This gem will include a custom FormBuilder instead.

Using this gem in combination with SimpleForm or Formtastic will be still possible: follow the guidelines (of SimpleForm/Formtastic) on how to create a custom input and use the Pwdcalc Form Helpers.

This makes it a lot easier to maintain the gem. Overwriting existing styles will not be an issue anymore.
